### ISSUE TITLE
Unable to build successfully for Android

### ISSUE THREAD

**Issue by surbhitrao** [chatwoot/chatwoot-mobile-app#376]
I'm getting the following error.
```

`FAILURE: Build failed with an exception.

 What went wrong:
Execution failed for task ':posthog-react-native:generateDebugRFile'.
This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
`
```

I've followed all the instructions in the guide. AndroidX is enabled in gradle.properties 
Maybe it's related to a new third-party library which was added recently.
My environment - Mac OS Big Sur. Tried even on windows 10 but got the same exact error.

**Comment by saleheenkhan** [comment]
Hello,
Facing the same error on windows 10.. anyone can help?

Thanks

**Comment by surbhitrao** [comment]
@saleheenkhan you need to create an account on posthog and add the required keys inside .env (make sure to rename env.example to .env)

**Comment by saleheenkhan** [comment]
@surbhitrao Thanks for your reply... I've already did that.. Still not working

**Comment by saleheenkhan** [comment]
Any Idea what more it could be or How did you solved yours?

**Comment by surbhitrao** [comment]
Can you please share the error logs

**Comment by saleheenkhan** [comment]
Hi @surbhitrao,

Here is the entire error log printout when I run the comment `yarn android` 


```
info Installing the app...
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :app
Reading env from: .env

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:firebase.bom using default value: 28.3.1
:react-native-firebase_app:play.play-services-auth using default value: 19.2.0
:react-native-firebase_app package.json found at C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:version set from package.json: 12.6.0 (12,6,0 - 12006000)
:react-native-firebase_app:android.compileSdk using custom value: 29
:react-native-firebase_app:android.targetSdk using custom value: 29
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\react-native\android

> Configure project :react-native-firebase_messaging
:react-native-firebase_messaging package.json found at C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\@react-native-firebase\messaging\package.json
:react-native-firebase_app package.json found at C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_messaging:firebase.bom using default value: 28.3.1
:react-native-firebase_messaging package.json found at C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\@react-native-firebase\messaging\package.json
:react-native-firebase_messaging:version set from package.json: 12.6.0 (12,6,0 - 12006000)
:react-native-firebase_messaging:android.compileSdk using custom value: 29
:react-native-firebase_messaging:android.targetSdk using custom value: 29
:react-native-firebase_messaging:android.minSdk using custom value: 21
:react-native-firebase_messaging:reactNativeAndroidDir C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\react-native\android

> Task :posthog-react-native:generateDebugRFile FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
178 actionable tasks: 2 executed, 176 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01      
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01    
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01      
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01      
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01    
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01      

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':posthog-react-native:generateDebugRFile'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.core:core:1.0.1, androidx.versionedparcelable:versionedparcelable:1.0.0, androidx.fragment:fragment:1.0.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.appcompat:appcompat:1.0.2, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.interpolator:interpolator:1.0.0, androidx.loader:loader:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.viewpager:viewpager:1.0.0, androidx.collection:collection:1.0.0, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.lifecycle:lifecycle-common:2.0.0, androidx.arch.core:core-common:2.0.0, androidx.annotation:annotation:1.0.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.lifecycle:lifecycle-viewmodel:2.0.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0, androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.lifecycle:lifecycle-runtime:2.0.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclayoutinflater:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1, androidx.print:print:1.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':posthog-react-native:generateDebugRFile'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.core:core:1.0.1, androidx.versionedparcelable:versionedparcelable:1.0.0, androidx.fragment:fragment:1.0.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.appcompat:appcompat:1.0.2, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.interpolator:interpolator:1.0.0, androidx.loader:loader:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.viewpager:viewpager:1.0.0, androidx.collection:collection:1.0.0, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.lifecycle:lifecycle-common:2.0.0, androidx.arch.core:core-common:2.0.0, androidx.annotation:annotation:1.0.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.lifecycle:lifecycle-viewmodel:2.0.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0, androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.lifecycle:lifecycle-runtime:2.0.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclayoutinflater:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1, androidx.print:print:1.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s

    at makeError (C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\execa\index.js:174:9)
    at C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\eva_k\StudioProjects\chatwoot-mobile-app\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by surbhitrao** [comment]
hi @saleheenkhan 
please try the following steps:
1. inside android/build.gradle make the following changes
`  dependencies {
       classpath("com.android.tools.build:gradle:3.5.3") 
       classpath 'com.google.gms:google-services:4.3.3'
    }`
    
2. Replace the ndkVersion inside android/build.gradle  with your locally available ndkVersion


The error comes because I believe there is some compatibility issue with androidx and the gradle version used in this repo.

**Comment by muhsin-k** [comment]
@saleheenkhan Can you please share the contents of the file `gradle.properties` in the `android/app/gradle.properties` folder

**Comment by saleheenkhan** [comment]
I all Thanks for showing up for help 
I have solved the problem by moving the `gradle.properties` from `/android/app/` folder to `/android/` folder

btw here is my `gradle.properties` file

```
android.useAndroidX=true
android.enableJetifier=true
FLIPPER_VERSION=0.54.0
org.gradle.jvmargs=-Xmx4608m
```
